#!/usr/bin/env bash
# Regenerate the golden traces in testdata/golden/ from testdata/programs/*.s.
#
#   tools/oracle/gen-golden.sh            # build the oracle and regenerate everything
#   KEEP_PLAIN=1 tools/oracle/gen-golden.sh   # also keep uncompressed .trace files
#
# Each trace is stored gzip-compressed (gzip -9 -n, no name/timestamp) as
# <prog>.<cfg>.trace.gz: uncompressed, the full set is ~2 GB (the per-cycle H line
# alone is up to 15 KB). Decompressed content is exactly `oracle <prog.s> <flags>`.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
ORACLE_DIR="$ROOT/tools/oracle"
PROGS="$ROOT/testdata/programs"
GOLDEN="$ROOT/testdata/golden"
ORACLE="$ORACLE_DIR/build/oracle"
MAX=5000
# Default keyboard input for programs that ask for it (CONTROL=8 number, CONTROL=9 char).
DEFAULT_INPUT=$'5\n3.5\na\n5\n3.5\na\n5\n3.5\na\n5\n3.5\na'

CONFIG_NAMES=(default nofwd ds btb lat)
config_flags() {
	case "$1" in
	default) echo "" ;;
	nofwd) echo "--forwarding 0" ;;
	ds) echo "--delayslot 1" ;;
	btb) echo "--btb 1" ;;
	lat) echo "--add 2 --mul 3 --div 10" ;;
	esac
}

make -s -C "$ORACLE_DIR"
mkdir -p "$GOLDEN"
rm -f "$GOLDEN"/*.trace "$GOLDEN"/*.trace.gz

needs_input() { # $1 = trace file: true if the run stopped waiting for keyboard input
	grep -q '^INPUT EOF$' "$1"
}

MANIFEST="$GOLDEN/MANIFEST.txt"
{
	echo "# Golden traces generated by tools/oracle/gen-golden.sh"
	echo "# Oracle: WinMIPS64 v1.60 (third_party/winmips64-andoni, commit $(cat "$ROOT/third_party/winmips64-andoni/UPSTREAM_COMMIT"))"
	echo "# Columns: trace | program | flags (always plus --max $MAX) | input file | assembled | cycles instructions"
	echo "# Traces are gzip -9 -n; the content is the stdout of: oracle <program> <flags> --max $MAX [--input <file>]"
} > "$MANIFEST"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

for src in "$PROGS"/*.s; do
	prog="$(basename "$src" .s)"
	input="$GOLDEN/$prog.input"
	# Detect keyboard input: run once without input; INPUT EOF means CONTROL=8/9 was used.
	if [ ! -f "$input" ]; then
		"$ORACLE" "$src" --max "$MAX" > "$tmp"
		if needs_input "$tmp"; then
			printf '%s\n' "$DEFAULT_INPUT" > "$input"
		fi
	fi
	for cfg in "${CONFIG_NAMES[@]}"; do
		flags="$(config_flags "$cfg")"
		args=()
		# shellcheck disable=SC2206
		[ -n "$flags" ] && args=($flags)
		inarg=()
		inname="-"
		if [ -f "$input" ]; then
			inarg=(--input "$input")
			inname="$(basename "$input")"
		fi
		out="$GOLDEN/$prog.$cfg.trace"
		"$ORACLE" "$src" ${args[@]+"${args[@]}"} --max "$MAX" ${inarg[@]+"${inarg[@]}"} > "$out"
		if head -1 "$out" | grep -q '^ASM OK'; then asm=ok; else asm=err; fi
		endl="$(grep '^END ' "$out" | sed 's/^END //' || true)"
		[ -z "$endl" ] && endl="-"
		printf '%s.trace.gz | %s.s | %s | %s | %s | %s\n' "$prog.$cfg" "$prog" "${flags:-(none)}" "$inname" "$asm" "$endl" >> "$MANIFEST"
		if [ "${KEEP_PLAIN:-0}" = "1" ]; then
			gzip -9 -n -c "$out" > "$out.gz"
		else
			gzip -9 -n -f "$out"
		fi
	done
done

# Oracle self-test (I/O and keyboard input), kept next to the oracle sources.
"$ORACLE" "$ORACLE_DIR/tests/io.s" --input "$ORACLE_DIR/tests/io.input" --max "$MAX" > "$ORACLE_DIR/tests/io.default.trace"

echo "golden traces written to $GOLDEN ($(ls "$GOLDEN"/*.trace.gz | wc -l | tr -d ' ') files)"
